server:
  port: 0

spring:
  application:
    name: order-service
  datasource:
#    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/mydb
#      driver-class-name: org.mariadb.jdbc.Driver
#      username: root
#      password: test1357
    url: jdbc:mariadb://localhost:3306/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: test1357
#  h2:
#    console:
#      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

