server:
  port: 8761

spring:
  application:
    name: discoveryservice # Microservice ID

eureka:
  client:
    register-with-eureka: false # Prevent self-registration
    fetch-registry: false # Prevent self-registration

