server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: file:///Users/bigth8/Projects/msa/e-commerce/config-repo # Use local repository